HEAPFLOW_EQU db 'equ', 0
HEAPFLOW_PT db 'pt', 0
HEAPFLOW_PTF db 'ptf', 0
HEAPFLOW_LPT db 'lpt', 0
HEAPFLOW_LPTF db 'lptf', 0
HEAPFLOW_IF db 'if', 0
HEAPFLOW_JMP db 'jmp', 0
HEAPFLOW_WHILE db 'while', 0
HEAPFLOW_RETURN db 'return', 0
HEAPFLOW_INT db 'int', 0
HEAPFLOW_DEL db 'del', 0
HEAPFLOW_DELF db 'delf', 0
HEAPFLOW_BREAK db 'break', 0
HEAPFLOW_CONTINUE db 'continue', 0
HEAPFLOW_IN db 'in', 0
HEAPFLOW_OUT db 'out', 0
